import { 
  Terminal, 
  Database, 
  Users, 
  BarChart3, 
  Cloud, 
  ShieldAlert, 
  GitBranch, 
  MessageSquare,
  FileText,
  Server
} from 'lucide-react';
import { AppCategory, InternalTool, User, MarqueeItem } from './types';

export const MOCK_USER: User = {
  id: 'usr_8293',
  name: 'ALEXANDER K.',
  email: 'alex.k@company.internal',
  role: 'ENGINEER',
};

export const DEFAULT_MARQUEE_ITEMS: MarqueeItem[] = [
  { id: 'mq_1', text: "SYSTEM STATUS: NOMINAL", highlight: false },
  { id: 'mq_2', text: "ACTIVE INCIDENTS: 0", highlight: false },
  { id: 'mq_3', text: "LATENCY: 24ms", highlight: false },
  { id: 'mq_4', text: "NEXT MAINT WINDOW: FRI 22:00 EST", highlight: true, color: 'bg-brutal-black text-white' },
  { id: 'mq_5', text: "REMINDER: SUBMIT Q3 OKRS BY EOD", highlight: false },
  { id: 'mq_6', text: "SECURITY ALERT: UPDATE CHROME", highlight: true, color: 'bg-brutal-red text-white' },
  { id: 'mq_7', text: "JIRA TICKETS: 142 OPEN", highlight: false },
  { id: 'mq_8', text: "DEPLOY FREEZE: INACTIVE", highlight: false },
];

export const INTERNAL_TOOLS: InternalTool[] = [
  {
    id: 'tool_1',
    name: 'DEPLOY_MASTER',
    description: 'Production deployment pipeline controller. Handle with extreme caution.',
    url: '#',
    icon: Cloud,
    category: AppCategory.DEV_TOOLS,
    status: 'ONLINE',
    accessLevel: ['ENGINEER', 'ADMIN'],
  },
  {
    id: 'tool_2',
    name: 'DB_SHREDDER',
    description: 'Direct SQL access to staging and prod replicas. Read-only by default.',
    url: '#',
    icon: Database,
    category: AppCategory.DEV_TOOLS,
    status: 'ONLINE',
    accessLevel: ['ENGINEER'],
  },
  {
    id: 'tool_3',
    name: 'PEOPLE_OPS',
    description: 'Employee directory, payroll management, and time-off requests.',
    url: '#',
    icon: Users,
    category: AppCategory.HR_ADMIN,
    status: 'ONLINE',
    accessLevel: ['ADMIN', 'ENGINEER', 'PRODUCT', 'DESIGN'],
  },
  {
    id: 'tool_4',
    name: 'METRIC_VORTEX',
    description: 'Real-time business intelligence dashboard and revenue tracking.',
    url: '#',
    icon: BarChart3,
    category: AppCategory.ANALYTICS,
    status: 'MAINTENANCE',
    accessLevel: ['PRODUCT', 'ADMIN', 'DESIGN'],
  },
  {
    id: 'tool_5',
    name: 'INCIDENT_CMDR',
    description: 'PagerDuty aggregation and active incident war room management.',
    url: '#',
    icon: ShieldAlert,
    category: AppCategory.DEV_TOOLS,
    status: 'OFFLINE',
    accessLevel: ['ENGINEER', 'ADMIN'],
  },
  {
    id: 'tool_6',
    name: 'REPO_GATE',
    description: 'Internal git repository governance and audit logs.',
    url: '#',
    icon: GitBranch,
    category: AppCategory.DEV_TOOLS,
    status: 'ONLINE',
    accessLevel: ['ENGINEER'],
  },
  {
    id: 'tool_7',
    name: 'SLACK_BOT_HQ',
    description: 'Configuration for internal chat bots and automations.',
    url: '#',
    icon: MessageSquare,
    category: AppCategory.PRODUCTIVITY,
    status: 'ONLINE',
    accessLevel: ['ENGINEER', 'PRODUCT'],
  },
  {
    id: 'tool_8',
    name: 'DOCS_ARCHIVE',
    description: 'Legacy documentation and deprecated API references.',
    url: '#',
    icon: FileText,
    category: AppCategory.PRODUCTIVITY,
    status: 'ONLINE',
    accessLevel: ['ADMIN', 'ENGINEER', 'PRODUCT', 'DESIGN'],
  },
  {
    id: 'tool_9',
    name: 'INFRA_MAP',
    description: 'Visual topology of current AWS/GCP infrastructure state.',
    url: '#',
    icon: Server,
    category: AppCategory.DEV_TOOLS,
    status: 'ONLINE',
    accessLevel: ['ENGINEER'],
  },
  {
    id: 'tool_10',
    name: 'LOG_STREAMER',
    description: 'Raw log output from all microservices. High bandwidth usage.',
    url: '#',
    icon: Terminal,
    category: AppCategory.DEV_TOOLS,
    status: 'ONLINE',
    accessLevel: ['ENGINEER'],
  },
];